# Generated by Django 5.2 on 2025-08-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='api_categor_user_id_2b62fa_idx',
            old_name='api_categ_user_name_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='api_note_user_id_91ccaf_idx',
            old_name='api_note_user_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='api_note_user_id_0791e9_idx',
            old_name='api_note_user_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='api_tag_user_id_ef3bf5_idx',
            old_name='api_tag_user_name_idx',
        ),
    ]
